### ISSUE TITLE
Final things before registering

### ISSUE THREAD

**Issue by pat-alt** [JuliaTrustworthyAI/TaijaInteroperability.jl#10]
Good morning @kmariuszk, just a couple things before we register:

- [x] Add all necessary compat entries (see open PRs)
- [x] Set package version entry to 0.1.0 (or some other version you deem appropriate, but not 1.0.0-DEV)

**Comment by kmariuszk** [comment]
![image](https://github.com/JuliaTrustworthyAI/TaijaInteroperability.jl/assets/67654024/0a2af571-3f66-405f-805e-5c8b4e51ee8a)

"You do not have permission to modify this app on JuliaTrustworthyAI. Please contact an Organization Owner." Could you please take care of it?

**Comment by kmariuszk** [comment]
@JuliaRegistrator register
